config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root "blog_post#index"
  get "posts/new", to: "blog_post#new", as: :new_post
  get "posts/:id/edit", to: "blog_post#edit", as: :edit_post
  get "posts/:id", to: "blog_post#show", as: :posts
  patch "posts/:id", to: "blog_post#update", as: :patch_post
  post "posts/new/create", to: "blog_post#create", as: :create_post
  delete "posts/:id", to: "blog_post#destroy", as: :delete_post
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  has_rich_text :content

  validates :title, presence: true
  validates :content, presence: true

  scope :draft, -> { where(published_at: nil) }
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    return published_at.nil?
  end

  def published?
    return published_at? && published_at <= Time.current
  end

  def scheduled?
    return published_at? && published_at > Time.current
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/blog_post_controller.rb
class BlogPostController < ApplicationController
  before_action :authenticate_user! , except: [:index, :show]
  before_action :set_blog_post , except: [:index, :new, :create]

  def set_blog_post
    if user_signed_in?
      @blog_post = BlogPost.find_by(id: params[:id])
    else
      @blog_post = BlogPost.published.find_by(id: params[:id])
    end
  end
  def index
    if user_signed_in?
      @blog_posts = BlogPost.all
    else
      @blog_posts = BlogPost.published
    end
  end

  def show
    if !@blog_post.present?
      redirect_to root_path
    end
  rescue
    redirect_to root_path
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(get_params)

    if @blog_post.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if !@blog_post.present?
      redirect_to posts_path
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end

  def update
    if @blog_post.present?
      @blog_post.update(get_params)
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def get_params
    return params.require(:blog_post).permit(:title, :content, :published_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_post/_form.html.erb
<%= form_with model: blog_post, url: url do |form| %>

  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |error| %>
      <p style="color:red;"><%= error %></p>
    <% end %>
  <% end %>

  <div>
    <%= form.label :title %>
    <br />
    <%= form.text_field :title %>
  </div>
  <br />
  <div>
    <%= form.label :content %>
    <br />
    <%= form.rich_text_area :content %>
  </div>
  <div>
    <%= form.label :published_at %>
    <br />
    <%= form.datetime_select :published_at, include_blank: true %>
  </div>
  <br />
  <%= form.button "Create Post", class: "bg-blue-500 p-1 pl-6 pr-6 cursor-pointer hover:bg-blue-600 transition-colors rounded-lg text-white" %>
<% end %>

app/views/blog_post/edit.html.erb
<h1>Edit Blog Post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post, url: patch_post_path } %>
<br />
<%= button_to "Delete",  delete_post_path, method: :delete, class: "bg-red-500 p-1 pl-6 pr-6 cursor-pointer hover:bg-red-600 transition-colors rounded-lg text-white", data: { turbo_confirm: "Are you sure ?" } %>

app/views/blog_post/index.html.erb
<h1>My Blog</h1>

<% @blog_posts.each do |post| %>
  <div>
    <h2><%= link_to post.title, posts_path(post.id) %></h2>
  </div>
<% end %>

app/views/blog_post/new.html.erb
<h1>Create new post</h1>

<%= render partial: "form", locals: { blog_post: @blog_post, url: create_post_path } %>

app/views/blog_post/show.html.erb
<h1> <%= @blog_post.title %> </h1>
<h2> <%= @blog_post.content %> </h2>

<%= link_to "Go Back", root_path %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
    <% end %>

    <%= yield %>
  </body>
</html>